const D=window.EXAM_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='apMarvelShareV2';
const fresh=()=>({screen:'start',name:'',timed:true,current:0,answers:Array(70).fill(null),flags:[],frqAnswers:Array(12).fill(''),selected:[0],scores:{},remainingMCQ:4500,remainingFRQ:5400,sectionStart:0,final:null});let S=fresh(),tick=null,mem=null;
function getSave(){try{return localStorage.getItem(KEY)}catch(e){return mem}}function setSave(){const v=JSON.stringify(S);mem=v;try{localStorage.setItem(KEY,v)}catch(e){}}function clearSave(){mem=null;try{localStorage.removeItem(KEY)}catch(e){}}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function show(id){['start','mcq','frq','rubrics','results'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#top').classList.toggle('hidden',id==='start'||id==='results');scrollTo(0,0)}
function modal(title,body,ok,text='Continue'){ $('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalOK').textContent=text;$('#modal').classList.remove('hidden');const close=()=>$('#modal').classList.add('hidden');$('#modalCancel').onclick=close;$('#modalOK').onclick=()=>{close();ok&&ok()}}
function fmt(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}function timer(){clearInterval(tick);if(!S.timed){$('#timer').textContent='UNTIMED';return}tick=setInterval(()=>{let k=S.screen==='mcq'?'remainingMCQ':'remainingFRQ';S[k]=Math.max(0,S[k]-1);$('#timer').textContent=fmt(S[k]);setSave()},1000);$('#timer').textContent=fmt(S.screen==='mcq'?S.remainingMCQ:S.remainingFRQ)}
function references(){const a=D.references.stones.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join(''),b=D.references.eras.map(r=>`<tr><th>${esc(r[0])}</th><td>${esc(r[1])}</td></tr>`).join('');$('#refs').innerHTML=`<h3>Infinity Stone Reference</h3><table>${a}</table><h3>Era and Story Reference</h3><table>${b}</table>`}
function buildGrid(){let g=$('#qgrid');g.innerHTML='';D.questions.forEach((_,i)=>{let b=document.createElement('button');b.textContent=i+1;b.onclick=()=>{S.current=i;question();setSave()};g.appendChild(b)});progress()}
function progress(){let n=S.answers.filter(Boolean).length;$('#progress').textContent=`${n} of 70 answered`;$('#bar').style.width=(n/70*100)+'%';$$('#qgrid button').forEach((b,i)=>{b.classList.toggle('answered',!!S.answers[i]);b.classList.toggle('current',i===S.current);b.classList.toggle('flagged',S.flags.includes(i))})}
function question(){let i=S.current,q=D.questions[i];$('#qnum').textContent=`Question ${i+1} of 70`;$('#qtext').textContent=q.question;$('#choices').innerHTML=q.choices.map((x,j)=>{let L=String.fromCharCode(65+j);return `<label class="choice ${S.answers[i]===L?'selected':''}"><input type="radio" name="choice" value="${L}" ${S.answers[i]===L?'checked':''}><b>(${L})</b><span>${esc(x)}</span></label>`}).join('');$$('input[name=choice]').forEach(x=>x.onchange=()=>{S.answers[i]=x.value;question();setSave()});$('#prev').disabled=i===0;$('#next').classList.toggle('hidden',i===69);$('#submitMCQ').classList.toggle('hidden',i!==69);$('#flag').textContent=S.flags.includes(i)?'Unflag':'Flag';progress()}
function begin(resume=false){if(!resume){S=fresh();S.name=$('#name').value.trim()||'Anonymous Student';S.timed=$('#timed').checked;S.screen='mcq';S.sectionStart=Date.now();setSave()}show('mcq');$('#section').textContent='SECTION I';references();buildGrid();question();timer()}
function submitMCQ(){let n=S.answers.filter(x=>!x).length;modal('Submit Section I',`<p>You have <strong>${n}</strong> unanswered question${n===1?'':'s'}.</p><p>Answers cannot be changed after submission.</p>`,()=>{S.screen='frq';setSave();renderFRQ()},'Submit Section I')}
function renderFRQ(){show('frq');$('#section').textContent='SECTION II';timer();$('#frqList').innerHTML=D.frqs.map((f,i)=>`<article class="card frq ${S.selected.includes(i)?'selected':''}"><div class="frqhead"><h3>${esc(f.title)}</h3><label><input class="pick" data-i="${i}" type="checkbox" ${S.selected.includes(i)?'checked':''} ${i===0?'disabled':''}> ${i===0?'Required':'Count this response'}</label></div>${f.image?`<img src="${esc(f.image)}" alt="Visual source">`:''}<div>${f.parts.map(p=>`<p>${esc(p)}</p>`).join('')}</div><textarea data-i="${i}" placeholder="Write your response here...">${esc(S.frqAnswers[i])}</textarea></article>`).join('');$$('.frq textarea').forEach(t=>t.oninput=()=>{S.frqAnswers[+t.dataset.i]=t.value;setSave()});$$('.pick').forEach(c=>c.onchange=()=>{let i=+c.dataset.i;if(c.checked){if(S.selected.length>=5){c.checked=false;modal('Five responses maximum','<p>Question 1 plus four additional questions may count.</p>');return}S.selected.push(i)}else S.selected=S.selected.filter(x=>x!==i);setSave();renderFRQ()});$('#frqStatus').textContent=S.selected.length===5?'Five responses selected.':`Select ${5-S.selected.length} more response${5-S.selected.length===1?'':'s'}.`}
function submitFRQ(){if(S.selected.length!==5){modal('Select five responses','<p>Select Question 1 and exactly four additional questions.</p>');return}modal('Submit Section II','<p>You will now see the scoring rubrics. Your responses cannot be edited afterward.</p>',()=>{S.screen='rubrics';setSave();renderRubrics()},'View Rubrics')}
function renderRubrics(){clearInterval(tick);show('rubrics');$('#rubricList').innerHTML=S.selected.map(i=>{let r=D.rubrics[i];return `<article class="card frq"><h3>${esc(r.title)}</h3><details><summary><b>Show my response</b></summary><div class="notice" style="white-space:pre-wrap">${esc(S.frqAnswers[i]||'(No response)')}</div></details><div class="rubric"><b>Scoring guidance</b><ul>${r.guidance.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><label><b>Points:</b> <select class="score" data-i="${i}"><option value="">Select</option>${[0,1,2,3,4,5,6].map(n=>`<option value="${n}" ${String(S.scores[i])===String(n)?'selected':''}>${n} / 6</option>`).join('')}</select></label></div></article>`}).join('');$$('.score').forEach(x=>x.onchange=()=>{S.scores[x.dataset.i]=Number(x.value);setSave()})}
function calculate(){if(S.selected.some(i=>S.scores[i]===undefined)){modal('Score every response','<p>Select a 0–6 score for all five selected responses.</p>');return}let correct=S.answers.reduce((n,a,i)=>n+(a===D.questions[i].answer),0),frq=S.selected.reduce((n,i)=>n+Number(S.scores[i]||0),0),comp=Math.round((((correct/70)*45+(frq/30)*55))*10)/10,ap=comp>=75?5:comp>=60?4:comp>=45?3:comp>=30?2:1;S.final={correct,frq,comp,ap};S.screen='results';setSave();renderResults()}
function renderResults(){clearInterval(tick);show('results');let x=S.final,labels={5:'Extremely well qualified',4:'Well qualified',3:'Qualified',2:'Possibly qualified',1:'No recommendation'};$('#ap').textContent=x.ap;$('#resultName').textContent=S.name;$('#mMCQ').textContent=`${x.correct}/70`;$('#mFRQ').textContent=`${x.frq}/30`;$('#mComp').textContent=`${x.comp}%`;$('#resultText').innerHTML=`<strong>${labels[x.ap]}</strong><br>This unofficial estimate weights multiple choice at 45% and free response at 55%.`;$('#mcqReview').innerHTML=D.questions.map((q,i)=>{let a=S.answers[i],ok=a===q.answer;return `<div class="review"><b>${i+1}. ${esc(q.question)}</b><div class="${ok?'right':'wrong'}">Your answer: ${a?`(${a}) ${esc(q.choices[a.charCodeAt(0)-65])}`:'Unanswered'}</div>${ok?'':`<div class="right">Correct: (${q.answer}) ${esc(q.choices[q.answer.charCodeAt(0)-65])}</div>`}</div>`}).join('');$('#frqReview').innerHTML=S.selected.map(i=>`<div class="review"><b>${esc(D.frqs[i].title)}</b><div>${S.scores[i]} / 6</div></div>`).join('')}
function resume(){try{let x=JSON.parse(getSave());if(x)S=Object.assign(fresh(),x)}catch(e){}if(S.screen==='mcq')begin(true);else if(S.screen==='frq')renderFRQ();else if(S.screen==='rubrics')renderRubrics();else if(S.screen==='results'&&S.final)renderResults();else begin(true)}
function init(){let has=!!getSave();$('#resumeBtn').classList.toggle('hidden',!has);$('#clearBtn').classList.toggle('hidden',!has);$('#startBtn').onclick=()=>begin();$('#resumeBtn').onclick=resume;$('#clearBtn').onclick=()=>modal('Clear saved attempt','<p>This erases the saved answers on this device.</p>',()=>{clearSave();location.reload()},'Clear');$('#refsBtn').onclick=()=>{$('#refs').classList.toggle('hidden');$('#refsBtn').textContent=$('#refs').classList.contains('hidden')?'Show References':'Hide References'};$('#firstBlankBtn').onclick=()=>{let i=S.answers.findIndex(x=>!x);if(i>=0){S.current=i;question()}};$('#prev').onclick=()=>{if(S.current){S.current--;question();setSave()}};$('#next').onclick=()=>{if(S.current<69){S.current++;question();setSave()}};$('#flag').onclick=()=>{let i=S.current;S.flags=S.flags.includes(i)?S.flags.filter(x=>x!==i):[...S.flags,i];question();setSave()};$('#submitMCQ').onclick=submitMCQ;$('#submitFRQ').onclick=submitFRQ;$('#calc').onclick=calculate;$('#copy').onclick=async()=>{let t=`${S.name} — AP Marvel Digital Exam: estimated AP score ${S.final.ap}; MCQ ${S.final.correct}/70; FRQ ${S.final.frq}/30; composite ${S.final.comp}%.`;try{await navigator.clipboard.writeText(t);$('#copy').textContent='Copied!'}catch(e){prompt('Copy your result:',t)}};$('#restart').onclick=()=>modal('Start over','<p>This erases the saved attempt.</p>',()=>{clearSave();location.reload()},'Start Over')}
window.addEventListener('DOMContentLoaded',init);